# -*- coding: utf-8 -*-
"""Mean Shift Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LaXPKL0rdL69aNRm2DieVqKZfPHSzHtm
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import io, segmentation, color

# Load the lung nodule image
image = io.imread("/content/segment-R_022.png")

segment_img = image
# Perform mean shift clustering segmentation
segmented = segmentation.felzenszwalb(segment_img, scale=300, sigma=0.4, min_size=70)


# Display the original and segmented images
fig, ax = plt.subplots(1, 2, figsize=(10, 5))
ax[0].imshow(image)
ax[0].set_title("Original Image")
ax[0].axis("off")
ax[1].imshow(segmented)
ax[1].set_title("Segmented Image")
ax[1].axis("off")
plt.show()